version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - nest-api

  test-db:
    image: postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - nest-api

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - nest-api

networks:
  nest-api:
