<<<<<<< HEAD
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest

  adminer:
    image: adminer
    restart: always
=======
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest

  adminer:
    image: adminer
    restart: always
>>>>>>> 576dc1b (initial commit)
    